# -*- coding: utf-8 -*-
"""AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDR_xZHsluQxbIVAMENunE0lBEjxwEom
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

mnist = tf.keras.datasets.mnist
(x_train,y_train), (x_test,y_test) = mnist.load_data()

x_train, x_test = x_train/255.0, x_test/255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer = 'adam',
            loss = 'sparse_categorical_crossentropy',
            metrics=['accuracy'])

model.fit(x_train,y_train,epochs=2)

test_loss,test_acc = model.evaluate(x_test,y_test,verbose=2)
print(f"Test Accuracy: {test_acc*100:.2f}%\n")

import gradio as gr
import numpy as np
from PIL import ImageOps

def classify_digit(drawing):

    img = drawing['composite'].convert('L').resize((28, 28))

    img = ImageOps.invert(img)

    img_array = np.array(img).reshape(1, 28,28) / 255.0


    prediction = model.predict(img_array)


    return {str(i): float(prediction[0][i]) for i in range(10)}


label = gr.Label(num_top_classes=3)
interface = gr.Interface(
    fn=classify_digit,
    inputs=gr.Sketchpad(type="pil"),
    outputs=label,
    title="Handwritten Digit Classifier",
    description="draw a number 0 to 9"
)


interface.launch(share=True)